// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	payroll "github.com/alimasyhur/go-payroll-service/internal/app/usecase/payroll"
	mock "github.com/stretchr/testify/mock"
)

// PayrollUsecase is an autogenerated mock type for the PayrollUsecase type
type PayrollUsecase struct {
	mock.Mock
}

// CreatePayroll provides a mock function with given fields: ctx, req
func (_m *PayrollUsecase) CreatePayroll(ctx context.Context, req payroll.CreatePayrollRequest) (payroll.CreatePayrollResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayroll")
	}

	var r0 payroll.CreatePayrollResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, payroll.CreatePayrollRequest) (payroll.CreatePayrollResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, payroll.CreatePayrollRequest) payroll.CreatePayrollResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(payroll.CreatePayrollResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, payroll.CreatePayrollRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayrollUsecase creates a new instance of PayrollUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayrollUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PayrollUsecase {
	mock := &PayrollUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
