// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alimasyhur/go-payroll-service/internal/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// AuditLog is an autogenerated mock type for the AuditLog type
type AuditLog struct {
	mock.Mock
}

// CreateAuditLog provides a mock function with given fields: ctx, payload
func (_m *AuditLog) CreateAuditLog(ctx context.Context, payload entity.AuditLog) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.AuditLog) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLog creates a new instance of AuditLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLog {
	mock := &AuditLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
