// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alimasyhur/go-payroll-service/internal/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// Overtime is an autogenerated mock type for the Overtime type
type Overtime struct {
	mock.Mock
}

// CreateOvertime provides a mock function with given fields: ctx, payload
func (_m *Overtime) CreateOvertime(ctx context.Context, payload entity.Overtime) (entity.Overtime, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateOvertime")
	}

	var r0 entity.Overtime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Overtime) (entity.Overtime, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Overtime) entity.Overtime); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(entity.Overtime)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Overtime) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListByUserDaterange provides a mock function with given fields: ctx, userUUID, startDate, endDate
func (_m *Overtime) GetListByUserDaterange(ctx context.Context, userUUID string, startDate string, endDate string) ([]entity.Overtime, error) {
	ret := _m.Called(ctx, userUUID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetListByUserDaterange")
	}

	var r0 []entity.Overtime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]entity.Overtime, error)); ok {
		return rf(ctx, userUUID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []entity.Overtime); ok {
		r0 = rf(ctx, userUUID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Overtime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userUUID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneByUserDate provides a mock function with given fields: ctx, userUUID, date
func (_m *Overtime) GetOneByUserDate(ctx context.Context, userUUID string, date string) (entity.Overtime, error) {
	ret := _m.Called(ctx, userUUID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetOneByUserDate")
	}

	var r0 entity.Overtime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entity.Overtime, error)); ok {
		return rf(ctx, userUUID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entity.Overtime); ok {
		r0 = rf(ctx, userUUID, date)
	} else {
		r0 = ret.Get(0).(entity.Overtime)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userUUID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOvertime creates a new instance of Overtime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOvertime(t interface {
	mock.TestingT
	Cleanup(func())
}) *Overtime {
	mock := &Overtime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
