// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alimasyhur/go-payroll-service/internal/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// Payroll is an autogenerated mock type for the Payroll type
type Payroll struct {
	mock.Mock
}

// CreatePayroll provides a mock function with given fields: ctx, payload
func (_m *Payroll) CreatePayroll(ctx context.Context, payload entity.Payroll) (entity.Payroll, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayroll")
	}

	var r0 entity.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Payroll) (entity.Payroll, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Payroll) entity.Payroll); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(entity.Payroll)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Payroll) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneByPeriodUUID provides a mock function with given fields: ctx, periodUUID
func (_m *Payroll) GetOneByPeriodUUID(ctx context.Context, periodUUID string) (entity.Payroll, error) {
	ret := _m.Called(ctx, periodUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOneByPeriodUUID")
	}

	var r0 entity.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Payroll, error)); ok {
		return rf(ctx, periodUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Payroll); ok {
		r0 = rf(ctx, periodUUID)
	} else {
		r0 = ret.Get(0).(entity.Payroll)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, periodUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPayroll creates a new instance of Payroll. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayroll(t interface {
	mock.TestingT
	Cleanup(func())
}) *Payroll {
	mock := &Payroll{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
